# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LeetCodeAlgomooc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LeetCodeAlgomooc
  pod 'Masonry', :git => 'https://github.com/clayzhu/Masonry.git'

end
